name: Node.js CI

on:
  push:
    branches: [main, dev, backend_dev, frontend_dev]
  pull_request_target:
    branches: [main, dev, backend_dev, frontend_dev]

jobs:
  build: 
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [15.x, 16.x, 17.x, 18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create env file for test environment        
        run: |
          cd ./API/src
          touch ./.env.test          
          echo "${{secrets.ENV_TEST}}" >> ./.env.test
          cat .env.test
        shell: bash

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          cd ./API/src
          npm install
          npm run test
