name: Node.js CI

on:
  push:
    branches: [main, dev, backend_dev, frontend_dev]
  pull_request:
    branches: [main, dev, backend_dev, frontend_dev]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x, 16.x, 17.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Create env file for test environment
        run: |
          cd ./API/src
          touch ./.env.test
          pwd
          ls -lf
          echo "this is a test sdlkfal;sdjflas;dkjf" >> ./env.test
          cat .env.test

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          cd ./API/src
          cat ./.env.test
          pwd
          npm install
          npm run test
