name: Merge dev Into Main

on:
  schedule:
    - cron: "00 13 * * FRI"
    # minute (0 - 59), hour (0 - 23), day of month (1 - 31), month(1 - 12 or JAN-DEC), day of week (0 - 6 or SUN-SAT)

# Set up the Continuous Integration job

jobs:
  main:
    name: Create PR Release to Main
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ADD_TO_PROJECT_PAT2 }}

      # https://github.com/marketplace/actions/github-pull-request-action
      - name: create pull request
        uses: repo-sync/pull-request@v2
        with:
          destination_repository: ""        # If blank, default: checked out repository or triggered repository
          source_branch: "dev"
          github_token: ${{ secrets.ADD_TO_PROJECT_PAT2 }}
          destination_branch: "main"
          pr_title: "[Automated] Merge ${{ github.ref_name }} into ${{ github.event.repository.default_branch }}"
          pr_body: "Automated Pull Request"
          pr_label: "auto-pr"                               # Comma-separated list (no spaces)
          pr_milestone: "Milestone 1"                       # Milestone name
