name: Extract and compile translation
on:
  pull_request_target:
    types:
      - opened
    branches:
      - "main"

jobs:
  if_merged:
    if: github.event.pull_request.head.ref == 'l10n_main' && github.event.pull_request.merged == true
    name: Enter client directory
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Update source code
        run: |
          npm run compile

      - name: Commit report
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-username@users.noreply.github.com'
          git add -A
          git commit -m "Translation compiled and extracted"
          git push origin l10n_main
