name: Weekly PR from CICD dev to main

on:
  schedule:
    - cron: '*/2 * * * *' # every 2 minutes
    # - cron: '0 0 * * 1' # every Monday at 00:00

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get the current date
      id: date
      run: echo "::set-output name=current_date::$(date)"

    - name: Commit and push changes
      run: |
        git config --local user.email "moocsprbot@oscsa.com"
        git config --local user.name "PR Bot"
        git add .
        git commit -m "auto commit $(steps.date.outputs.current_date)"
        git push origin cicd_dev
      
    - name: Create pull request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.REPO_TOKEN }}
        commit-message: "auto commit $(steps.date.outputs.current_date)"
        title: "Weekly PR $(steps.date.outputs.current_date)"
        head: backend_dev
        base: cicd_dev
