name: Weekly PR from CICD dev to main

on:
  workflow_dispatch: 

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
          token: ${{ secrets.ADD_TO_PROJECT_PAT2 }}

    - name: Get the current date
      id: date
      run: echo "date=$(date)" >> $GITHUB_STATE

    - name: Create pull request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.REPO_TOKEN }}
        commit-message: "auto commit date: $(cat $GITHUB_STATE | grep date | cut -d '=' -f 2)"
        title: "Weekly PR date: $(cat $GITHUB_STATE | grep date | cut -d '=' -f 2)"
        head: backend_dev
        base: cicd_dev

